#  appveyor.yml

clone_folder: c:\projects\postgresql\contrib\plr

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
install:
  - appveyor downloadfile https://cran.rstudio.com/bin/windows/base/R-3.4.2-win.exe 
  - R-3.4.2-win.exe /silent
  - git clone https://git.postgresql.org/git/postgresql.git c:\projects\src\postgresql
  - cd c:\projects\src\postgresql
  - git checkout REL_10_0
  - cd ..
  - xcopy postgresql c:\projects\
  - cd c:\projects\postgresql
  - cinst winflexbison
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  
before_build:
  - net user testuser Blurfl9426! /add
  - rename c:\ProgramData\chocolatey\bin\win_flex.exe flex.exe
  - rename c:\ProgramData\chocolatey\bin\win_bison.exe bison.exe
  - cd c:\projects\src\postgresql
  - perl c:\projects\postgresql\contrib\plr\buildsetup.pl
  
build:
  project: c:\projects\src\postgresql\pgsql.sln
  
configuration:
  - Release
  
test_script:
  - echo redirect escape ^> foo.bar
  - echo echo script running > c:\projects\postgresql\test_script.bat
  - echo cd %cd%\src\tools\msvc >> c:\projects\postgresql\test_script.bat
  - echo SET PATH=%PATH% >> c:\projects\postgresql\test_script.bat
  - perl -e "print q{.\vcregress check > regression.out}, qq{\n};" >> c:\projects\postgresql\test_script.bat
  - type c:\projects\postgresql\test_script.bat
  - psexec -u testuser -p Blurfl9426!  c:\projects\postgresql\test_script.bat
  - type src\tools\msvc\regression.out

  
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    
