#  appveyor.yml


init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
install:
  - appveyor downloadfile https://cran.rstudio.com/bin/windows/base/R-3.4.2-win.exe 
  - R-3.4.2-win.exe /VERYSILENT /dir=C:\R-3.4.2
  - git clone https://git.postgresql.org/git/postgresql.git c:\projects\postgresql
  - cd c:\projects\postgresql
  - git checkout REL_10_0
  - mv c:\projects\plr contrib
  - cinst winflexbison
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  
before_build:
  - net user testuser Blurfl9426! /add
  - rename c:\ProgramData\chocolatey\bin\win_flex.exe flex.exe
  - rename c:\ProgramData\chocolatey\bin\win_bison.exe bison.exe
  - cd c:\projects\postgresql
  - perl c:\projects\postgresql\contrib\plr\buildsetup.pl
  - dumpbin /EXPORTS C:\R-3.4.2\bin\x64\R.dll > c:\projects\postgresql\contrib\plr\R.symbols
  - awk 'NR > 19 { print }' < c:\projects\postgresql\contrib\plr\R.symbols  | tr -s ' ' |cut -d ' ' -f 5 > c:\projects\postgresql\contrib\plr\R.stripped
  - cat c:\projects\postgresql\contrib\plr\header.def c:\projects\postgresql\contrib\plr\R.stripped > c:\projects\postgresql\contrib\plr\R.def
  - lib /def:c:\projects\postgresql\contrib\plr\R.def /out:C:\R-3.4.2\bin\x64\R.lib

build:
  project: c:\projects\postgresql\pgsql.sln
  
configuration:
  - Release
  
test_script:
  - echo redirect escape ^> foo.bar
  - echo echo script running > c:\projects\postgresql\test_script.bat
  - echo cd %cd%\src\tools\msvc >> c:\projects\postgresql\test_script.bat
  - echo SET PATH=%PATH% >> c:\projects\postgresql\test_script.bat
  - perl -e "print q{.\vcregress check > regression.out}, qq{\n};" >> c:\projects\postgresql\test_script.bat
  - type c:\projects\postgresql\test_script.bat
  - psexec -u testuser -p Blurfl9426!  c:\projects\postgresql\test_script.bat
  - type src\tools\msvc\regression.out

  
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    
